import baseConfig from "@repo/eslint-config"
import { next } from "@repo/eslint-config/configs"

/** @type {import("eslint").Linter.Config[]} */
export default [
  // Generated by Next.js on every dev/build run
  { ignores: ["next-env.d.ts"] },
  ...baseConfig,
  ...next,
  {
    // Standalone CLI/data scripts — relax rules that only make sense for app code
    files: ["scripts/**/*.{ts,mjs,js}"],
    rules: {
      "no-console": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/prefer-top-level-await": "off",
      "sonarjs/cognitive-complexity": "off",
      "turbo/no-undeclared-env-vars": "off",
    },
  },
]
