"use client"

/* eslint-disable react/no-unknown-property */

import { useTexture } from "@react-three/drei"
import { Canvas, useFrame } from "@react-three/fiber"
import { Suspense, useEffect, useMemo, useRef } from "react"
import * as THREE from "three"

import { cn } from "@/lib/styles"

// ── Specular mask images ─────────────────────────────────────────────────────
//
// We sample the *-specular.png files (solid white continent silhouette on
// transparent background, generated by generate-continent-specular-maps.mjs)
// rather than the pre-rendered *-dots.png files.  The dot PNGs have tiny
// 3–5 px circles on a 1536 px canvas that are hard to hit reliably at any
// reasonable sample step.  The specular masks have solid opaque regions — any
// pixel with alpha > 0 is guaranteed continent land.

const SPECULAR_IMAGES: Record<string, string> = {
  africa: "/images/globe/continent-africa-specular.png",
  americas: "/images/globe/continent-americas-specular.png",
  asia: "/images/globe/continent-asia-specular.png",
  europe: "/images/globe/continent-europe-specular.png",
  oceania: "/images/globe/continent-oceania-specular.png",
  "north-america": "/images/globe/continent-americas-specular.png",
  "south-america": "/images/globe/continent-americas-specular.png",
}

// ── Shaders — identical to KnowledgeGlobeCanvas ──────────────────────────────

const DOT_VERT = `
  attribute float intensity;
  attribute float size;
  uniform float uSizeScale;
  varying float vIntensity;
  void main() {
    vIntensity = intensity;
    vec3 dir = normalize(position);
    vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
    float sizeFactor = 0.34 + intensity * 0.18;
    gl_PointSize = size * uSizeScale * sizeFactor * (122.0 / -mvPosition.z) * 0.62;
    gl_Position  = projectionMatrix * mvPosition;
  }
`
const DOT_FRAG = `
  uniform vec3 uBaseColor;
  uniform vec3 uHighlightColor;
  varying float vIntensity;
  void main() {
    float d    = distance(gl_PointCoord, vec2(0.5));
    float halo = smoothstep(0.38, 0.10, d);
    float core = smoothstep(0.12, 0.00, d);
    float alpha = (halo * 0.45 + core * 1.2) * (0.34 + vIntensity * 0.28) * 1.5;
    if (alpha < 0.01) discard;
    vec3 color = mix(uBaseColor, uHighlightColor, core * 0.22 + vIntensity * 0.18)
               * (1.0 + halo * 0.08);
    gl_FragColor = vec4(color, alpha);
  }
`

const GLOW_VERT = `
  attribute float activity;
  attribute float intensity;
  attribute float phase;
  attribute float size;
  uniform float uSizeScale;
  uniform float uTime;
  varying float vActivity;
  varying float vIntensity;
  varying float vShimmer;
  void main() {
    float shimmer =
      0.975
      + 0.05  * sin(uTime * 0.22 + phase * 0.93)
      + 0.018 * sin(uTime * 0.11 + phase * 1.71 + intensity * 2.4);
    float actMask     = smoothstep(0.14, 0.74, activity);
    float densityMask = smoothstep(0.48, 0.92, intensity * 0.42 + activity * 0.88);
    vec4 mvPosition   = modelViewMatrix * vec4(position, 1.0);
    vActivity  = activity;
    vIntensity = intensity;
    vShimmer   = shimmer;
    float cloudSize = 0.92 + actMask * 0.9 + densityMask * 0.35;
    gl_PointSize = size * uSizeScale * cloudSize * shimmer * (122.0 / -mvPosition.z) * 0.82;
    gl_Position  = projectionMatrix * mvPosition;
  }
`
const GLOW_FRAG = `
  uniform vec3 uGlowColor;
  varying float vActivity;
  varying float vIntensity;
  varying float vShimmer;
  void main() {
    vec2  c     = gl_PointCoord - vec2(0.5);
    float r     = length(c) * 2.0;
    float broad = exp(-r * r * 2.2);
    float mid   = exp(-r * r * 4.8);
    float coreG = exp(-r * r * 8.2);
    float cMask = smoothstep(0.16, 0.72, vActivity)
                * smoothstep(0.54, 0.96, vIntensity + vActivity * 0.34);
    float alpha = (broad * 0.03 + mid * 0.015 + coreG * 0.004)
                * (0.78 + vIntensity * 0.24)
                * (0.72 + vActivity  * 0.48)
                * cMask * vShimmer;
    if (alpha < 0.001) discard;
    gl_FragColor = vec4(uGlowColor * (0.9 + vActivity * 0.2), alpha);
  }
`

// ── Seeded RNG ───────────────────────────────────────────────────────────────

function makeRng(seed: number) {
  let s = Math.trunc(seed)

  return (): number => {
    s = Math.trunc(s + 0x6d2b79f5)
    let v = Math.imul(s ^ (s >>> 15), 1 | s)
    v = (v + Math.imul(v ^ (v >>> 7), 61 | v)) ^ v

    return ((v ^ (v >>> 14)) >>> 0) / 4294967296
  }
}

// ── Geometry from specular mask ──────────────────────────────────────────────
//
// World layout:
//   The specular masks are 1536×1536 (square, continent centred with padding).
//   We map them to a 9×9 world-unit plane.  At camera z=5.5 with FOV 55° the
//   viewport shows ~5.7 units tall × ~10.2 units wide, so the continent bleeds
//   slightly off the left/right edges (immersive) while staying centred.
//
// Sample strategy:
//   Walk a 12-pixel grid.  Any pixel with alpha > 30 is land — the specular
//   masks have solid opaque regions so every on-continent sample is reliable.
//   A 5 % random cull avoids mechanical regularity.

const WORLD_SIZE = 9 // world units the 1536 px image maps to
const SAMPLE_STEP = 7
const ALPHA_MIN = 30
const CULL_RATE = 0.03

function buildGeometry(
  image: HTMLImageElement,
  seed: number
): THREE.BufferGeometry {
  const canvas = document.createElement("canvas")
  const ctx = canvas.getContext("2d", { willReadFrequently: true })
  if (!ctx) return new THREE.BufferGeometry()

  const iw = image.naturalWidth || image.width
  const ih = image.naturalHeight || image.height
  if (iw === 0 || ih === 0) return new THREE.BufferGeometry()

  canvas.width = iw
  canvas.height = ih
  ctx.drawImage(image, 0, 0)
  const pixels = ctx.getImageData(0, 0, iw, ih).data

  const positions: number[] = []
  const sizes: number[] = []
  const intensities: number[] = []
  const phases: number[] = []
  const activities: number[] = []

  const rng = makeRng(seed)

  for (let y = 0; y < ih; y += SAMPLE_STEP) {
    for (let x = 0; x < iw; x += SAMPLE_STEP) {
      const alpha = pixels[(y * iw + x) * 4 + 3]!
      if (alpha < ALPHA_MIN) continue
      if (rng() < CULL_RATE) continue

      // Small jitter so grid regularity is broken up
      const jx = x + (rng() - 0.5) * SAMPLE_STEP * 0.6
      const jy = y + (rng() - 0.5) * SAMPLE_STEP * 0.6

      const wx = (jx / iw - 0.5) * WORLD_SIZE
      const wy = (0.5 - jy / ih) * WORLD_SIZE
      const wz = (rng() - 0.5) * 0.3 // shallow depth for subtle parallax

      positions.push(wx, wy, wz)
      sizes.push(0.78 + rng() * 0.42)
      intensities.push(0.5 + rng() * 0.5)
      phases.push(rng() * Math.PI * 2)
      activities.push(0.18 + rng() * 0.44) // moderate uniform activity
    }
  }

  if (positions.length === 0) return new THREE.BufferGeometry()

  const geo = new THREE.BufferGeometry()
  geo.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3))
  geo.setAttribute("size", new THREE.Float32BufferAttribute(sizes, 1))
  geo.setAttribute(
    "intensity",
    new THREE.Float32BufferAttribute(intensities, 1)
  )
  geo.setAttribute("phase", new THREE.Float32BufferAttribute(phases, 1))
  geo.setAttribute("activity", new THREE.Float32BufferAttribute(activities, 1))
  geo.computeBoundingSphere()

  return geo
}

// ── Scene component ──────────────────────────────────────────────────────────

function ContinentParticles({
  imageUrl,
  seed,
}: {
  imageUrl: string
  seed: number
}) {
  const texture = useTexture(imageUrl)
  const glowRef = useRef<THREE.ShaderMaterial>(null)

  const geo = useMemo(() => {
    const img =
      typeof HTMLImageElement !== "undefined" &&
      texture.image instanceof HTMLImageElement
        ? texture.image
        : null

    return img ? buildGeometry(img, seed) : new THREE.BufferGeometry()
  }, [texture.image, seed])

  useEffect(
    () => () => {
      geo.dispose()
    },
    [geo]
  )

  useFrame(({ clock }) => {
    if (glowRef.current?.uniforms.uTime) {
      glowRef.current.uniforms.uTime.value = clock.elapsedTime
    }
  })

  const dotUniforms = useMemo(
    () => ({
      uBaseColor: { value: new THREE.Color("#c3d8ee") },
      uHighlightColor: { value: new THREE.Color("#f7fbff") },
      uSizeScale: { value: 1.04 },
    }),
    []
  )

  const glowUniforms = useMemo(
    () => ({
      uGlowColor: { value: new THREE.Color("#76c9ff").multiplyScalar(1.18) },
      uSizeScale: { value: 1.18 },
      uTime: { value: 0 },
    }),
    []
  )

  return (
    <>
      <points geometry={geo}>
        <shaderMaterial
          depthWrite={false}
          fragmentShader={DOT_FRAG}
          toneMapped={false}
          transparent
          uniforms={dotUniforms}
          vertexShader={DOT_VERT}
        />
      </points>

      <points geometry={geo}>
        <shaderMaterial
          ref={glowRef}
          blending={THREE.AdditiveBlending}
          depthWrite={false}
          fragmentShader={GLOW_FRAG}
          toneMapped={false}
          transparent
          uniforms={glowUniforms}
          vertexShader={GLOW_VERT}
        />
      </points>
    </>
  )
}

// ── Seeds match generate-continent-specular-maps.mjs ────────────────────────

const SEEDS: Record<string, number> = {
  africa: 11,
  americas: 23,
  asia: 37,
  europe: 41,
  oceania: 53,
  "north-america": 23,
  "south-america": 23,
}

// ── Public export ────────────────────────────────────────────────────────────

export function ContinentDotCanvas({
  continentSlug,
  className,
}: {
  readonly continentSlug: string
  readonly className?: string
}) {
  const imageUrl = SPECULAR_IMAGES[continentSlug] ?? SPECULAR_IMAGES.europe!
  const seed = SEEDS[continentSlug] ?? 41

  return (
    <div className={cn("relative h-full w-full", className)}>
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(ellipse 65% 55% at 55% 42%, rgba(18,68,140,0.24) 0%, rgba(8,20,60,0.10) 48%, transparent 72%)",
        }}
      />

      <Canvas
        camera={{ fov: 55, position: [0, 0, 5.5] }}
        className="h-full w-full"
        dpr={[1, 1.5]}
        gl={{
          alpha: true,
          antialias: false,
          powerPreference: "high-performance",
          stencil: false,
        }}
        onCreated={({ gl }) => gl.setClearColor(0x000000, 0)}
        performance={{ min: 0.75 }}
      >
        <Suspense fallback={null}>
          <ContinentParticles imageUrl={imageUrl} seed={seed} />
        </Suspense>
      </Canvas>
    </div>
  )
}

Object.values(SPECULAR_IMAGES).forEach((url) => useTexture.preload(url))
